### ISSUE TITLE
Multi-lines value & trim

### ISSUE THREAD

**Issue by sanglierquipue** [evangelion1204/multi-ini#12]
Hi,

It looks like lines in multi-lines values are trimed, so that the result of the following entry : 

```
key1 = "
  aaaa
   bbbb"
```

is 
```
aaaa
bbbb
```
instead of

```
  aaaa
   bbbb
```

Can you add an option to keep space ?

**Comment by evangelion1204** [comment]
Hi,

yes you are right and this should not happen. I will take a look. From my point of view it makes sense to keep whitespaces in multilines as default.

**Comment by evangelion1204** [comment]
Sorry forgot to publish the new version, done now.

**Comment by sanglier91** [comment]
Hi !

I just try the new version (0.5.1), but got an error with ini file who works before. 

This ini file is ok:

```
[(U+Pu) métal H2O]
; loi incomplète
description="(U+Pu) métal modération H2OParamétrage de la modération en H/(U+Pu)"
```

But this the following throw me an error:
```
[(U+Pu) métal H2O]
; loi incomplète
description="(U+Pu) métal modération H2O
Paramétrage de la modération en H/(U+Pu)"
```

The error message:
```
H:\CDT\node_modules\multi-ini\lib\multi-ini-class.js:231
        _ref = this.getMultiKeyValue(line), key = _ref[0], value = _ref[1];
                                                      ^
TypeError: Cannot read property '0' of undefined
    at MultiIni.read (H:\CDT\node_modules\multi-ini\lib\multi-ini-class.js:231:55)
    at Object.module.exports.read (H:\CDT\node_modules\multi-ini\lib\multi-ini-class.js:318:21)
    at AP28M5.load (H:\CDT\calculation_schemes\ap28-m5.js:160:36)
    at null.<anonymous> (H:\CDT\calculation_scheme_loader.js:42:24)
    at Array.forEach (native)
    at CalculationSchemesLoader.loadAll (H:\CDT\calculation_scheme_loader.js:35:25)
    at Server.start (H:\CDT\server.js:53:17)
    at Object.<anonymous> (H:\CDT\server.js:234:8)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
```

**Comment by evangelion1204** [comment]
You can add now the options `line_breaks: 'windows'` to read your file without any problems, `unix` is the default value.
